version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux:latest"
        environment:
            SA_PASSWORD: "stone@123"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433